layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: derek-wacks
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  #- name: CSS
  #  web_url: https://github.com/topics/css
  #  image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Flux Marine
    web_url: https://https://www.fluxmarine.com/
    image_url: https://static.wixstatic.com/media/fc677f_7d98a69921c44167a88a246b05af6cb6~mv2.png/v1/fill/w_110,h_90,al_c,q_85,usm_0.66_1.00_0.01/Picture1_edited.webp
    description: In 2016 I co-founded a startup that builds fully electric boat motors. From a lab bench in Princeton's thermo lab, Flux Marine is now raising funding. 

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png

  - name: Art!
    web_url: https://derekwacks.github.io/art.html
    image_url: https://derekwacks.github.io/orb.jpg
    description: I had a brief stint welding metal sculptures that range from 12" in height to 5' from recycled materials. Inspirations ranged from Binary Search Trees to breakfast and the state of the world. I also wrote a novel (currently unpublished), "(Unauthentic) Smokey Hallow", about the escapades of an art dealer in New York. Needless to say, ridiculousness unfolds.
