layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 0
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name
      - discrete-math



social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: derek-wacks
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

current_projects:
  - name: Tempus
    image_url: https://derekwacks.github.io/betelgeuse.jpg
    description: Tempus will become a SaaS time management project that evolves our perception of passing time away from the 24 hour clock and standard work week. By adapting how we allocate tim, Tempus will allow us to live more thoughtful and productive lives. Currently, the project consists of several microservices running locally, on AWS Beanstalk, and on AWS EC2. These microservices (UserService, CatalogService and CommentService) house REST APIs using Flask with routes to HTTP requests that access a relational database instance on AWS RDS and a NoSql database instance on AWS DynamoDB. UserService also includes a user interface that implements Angular to provide a user registration form to submit entries to the relational database. This work is with Jillian Ross, in collaboration with Prof. Ferguson as an advisor. 

  - name: Does time fly? (yes, if you're a dehydrated mouse on a virtual four meter track)
    web_url: https://github.com/sophiakolak/6998-what-is-time/blob/main/6998_final_paper_AymanKolakWacks.pdf
    image_url: https://derekwacks.github.io/heatmap.jpg
    description: Using calcium imaging data provided by Walter Fischler in the Axel Lab, Yasmine Ayman, Sophia Kolak and I examine activity recorded from CA1 neurons during a virtual navigation task, where identical odors are presented at different points along a four meter track. It has been shown that place cells and internal path integrators are calibrated by these odor landmarks. Here we examine the role that the time cell network plays in temporally structuring the experience of moving through space. We compare time cell and place cell activity patterns during the task with and without odor, as well as during the reward period. We also assess the role of learning on time cell representations by examining the time cell patterns in no odor trials before and after learning. 


groups: 
  - name: Schiminovich Group
    web_url: https://sail.astro.columbia.edu/
    image_url: https://sail.astro.columbia.edu/sites/default/files/styles/cu_crop/public/content/CHaS%20Image%20Card.jpg?itok=3O8FgvxO
    description: I spent a summer designing optomechanical and structural aspects of CHaS (the Circumgalactic Hydrogen Alpha Integral Field Unit Spectrograph) to be used at the MDM Observatory, for Professor Schiminovich (PI). I specifically focused on optomechanical component integration and design of the carbon truss structure, performing finite-element-analysis along the way for structural optimization.

  - name: Steingart Group
    web_url: https://ceec.engineering.columbia.edu/people/daniel-steingart
    image_url: https://derekwacks.github.io/flir.jpg
    description: While residing on the homey 9th floor of Mudd... I designed a temperature control system with deadban heating & cooling functionality for a lithium cell test environment; experimented with Partial Integral Derivative algorithms for temperature control systems; researched & tinkered with remote Keithley instrument control (MQTT server using Mosquitto, nodeforwarder, WebREPL); and wrote code aiding graduate student research. The PI, Professor Steingart was in fact the faculty advisor at Princeton who signed off on electric boat motor R&D (see below) in the MAE department’s thermo lab. I don’t know if saying that gets Dan into trouble, but he has since come to Columbia anyways

topics:
  - name: Flux Marine
    web_url: https://www.fluxmarine.com/
    image_url: https://static.wixstatic.com/media/fc677f_7d98a69921c44167a88a246b05af6cb6~mv2.png/v1/fill/w_110,h_90,al_c,q_85,usm_0.66_1.00_0.01/Picture1_edited.webp
    description: I grew up spending summers on Lake George, NY, tinkering with everything from tractors to boat motors. A lifelong friend Ben Sorkin and I fell in love with antique and vintage race boats. In 2016 we co-founded a sustainable technology startup that builds fully electric boat motors. Though I have since stepped back to pursue my bachelor's degree, I am proud to say from a lab bench in Princeton's thermo lab, Flux Marine is now closing a round of funding.

#  - name: Tempus.Think
#    image_url: https://derekwacks.github.io/betelgeuse.jpg
#    description: Still in an early development stage, Tempus.Think is a SaaS time management project that evolves our perception of passing time away from the 24 hour clock and standard work week. By adapting how we allocate time, Tempus.Think allows us to live more thoughtful and productive lives. 


  - name: Art & Writings!
    web_url: https://derekwacks.github.io/art.html
    image_url: https://derekwacks.github.io/orb.jpg
    description: I had a brief stint welding metal sculptures from recycled steel. Inspirations ranged from Binary Search Trees to breakfast and the state of the world. I also wrote a novel (currently unpublished), "(Unauthentic) Smokey Hallow", about the escapades of an art dealer in New York and his trip across America. Needless to say, ridiculousness unfolds. I've also tried writing poetry (or what you could call poetry if you squint really hard and look the other way) and electronic music composition using Logic, Reason and Pro Tools (though I buried any creations deep in the caverns of Sound Cloud, hopefully never to be found). 

  - name: Out in *Neature*
    web_url: https://www.youtube.com/watch?v=Hm3JodBR-vs
    image_url: https://derekwacks.github.io/kangaroo.jpg
    description: I'm also an avid skier, coaching for a few seasons for the Olympic Regional Development Authority at Gore Mtn. in the Adirondacks and racing for Columbia in the USCSA. I've found causing mayhem in glades around the North-East keeps me from pulling my hair out when my code won't run. My licence plate reads "SHREDGNR". References available upon request. 

  - name: Going Ons About Town
    web_url: https://en.wikipedia.org/wiki/Overview_effect
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/The_Earth_seen_from_Apollo_17.jpg/1920px-The_Earth_seen_from_Apollo_17.jpg
    description: Stemming from a love of the Overview effect, I'm also involved in a few real estate projects around New York (including in Brooklyn and the Adirondacks)

futures:
  - name: Graduate school and Beyond
    description: My dream is to study self-awareness through the lens of computational neuroscience. I am obsessed with the emergent property of introspective thought (derived from assembling enough complex neural circuitry?), philosophical ramifications of this, and consequently how we can reverse-engineer this to build better computers (which in turn will THEN help us better understand the brain on a more intimate level). I am hoping to work in neural engineering to integrate brain machine interfaces into the human body to alter how we perceive reality (or fundamentally change reality if you don't believe in objectivity-- whatever floats your mental boat)

